"""Persistence and listing helpers the TUI needs that experiments/ and
target_system/ don't already expose. No statistics and no execution live
here — verdict computation is tui/verdict_logic.py, running attacks is
tui/execution.py; this module only reads/writes paths and shapes what's
on disk into something a screen can render.

Single-config checks (no paired arm, so experiments.runner.run_experiment
doesn't fit) reuse the exact same RunRecord/JSONL machinery as paired
experiments — arm is just left None — keyed by config_hash rather than an
experiment name. That keying is deliberate: re-running a single-config
check against the same config_hash resumes/extends the same file, giving
it the same "never re-run cached data" property paired experiments get
from experiments.runner.CacheIndex.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from experiments.persist import load_experiment_report, report_path
from experiments.runner import DEFAULT_RUNS_DIR
from target_system.config import DEFAULT_CONFIGS_DIR, SystemConfig, compute_config_hash, list_config_hashes, load_config, save_config
from target_system.factory import baseline_config
from target_system.logging_schema import RunRecord, read_run_records
from tui.formatting import describe_config_diff, preset_display_name
from tui.verdict_logic import ComparisonVerdict, SingleConfigSummary, compute_comparison_verdict, compute_single_config_summary

SINGLE_CONFIG_RUN_PREFIX = "single_"


def single_config_run_name(config_hash: str) -> str:
    return f"{SINGLE_CONFIG_RUN_PREFIX}{config_hash}"


def single_config_run_path(config_hash: str, runs_dir: Path = DEFAULT_RUNS_DIR) -> Path:
    return runs_dir / f"{single_config_run_name(config_hash)}.jsonl"


def load_single_config_records(config_hash: str, runs_dir: Path = DEFAULT_RUNS_DIR) -> list[RunRecord]:
    return list(read_run_records(single_config_run_path(config_hash, runs_dir)))


# --- config listing & diff ---------------------------------------------------


@dataclass(frozen=True)
class ConfigSummary:
    config_hash: str
    label: str
    model_name: str
    defensive_instruction: bool
    enforce_allowlist: bool
    n_agents: int
    description: str  # human-readable, generated by describe_config_for_humans — the primary label everywhere


def describe_config(
    config_hash: str, *, configs_dir: Path = DEFAULT_CONFIGS_DIR, baseline_hash: str | None = None
) -> ConfigSummary:
    config = load_config(config_hash, configs_dir=configs_dir)
    return ConfigSummary(
        config_hash=config_hash,
        label=config.label,
        model_name=config.model.model_name,
        defensive_instruction=config.defensive_instruction,
        enforce_allowlist=config.security.enforce_allowlist,
        n_agents=len(config.agents),
        description=describe_config_for_humans(config_hash, configs_dir=configs_dir, baseline_hash=baseline_hash),
    )


def list_configs(*, configs_dir: Path = DEFAULT_CONFIGS_DIR) -> list[ConfigSummary]:
    """Newest first — list_config_hashes already sorts by mtime desc.
    baseline_hash is resolved once here (not once per config) since
    default_baseline_hash's save_config call is cheap but pointless to
    repeat N times for a list of N configs."""
    baseline_hash = default_baseline_hash(configs_dir=configs_dir)
    return [describe_config(h, configs_dir=configs_dir, baseline_hash=baseline_hash) for h in list_config_hashes(configs_dir=configs_dir)]


def default_baseline_hash(*, configs_dir: Path = DEFAULT_CONFIGS_DIR) -> str:
    """The content hash of target_system.factory.baseline_config() with no
    overrides — every config description is generated relative to this.
    Pure — never touches disk, so calling this alone (e.g. to check "is
    configs_dir empty") never has the side effect of writing anything.
    Diffing *against* this hash needs the baseline to actually be saved;
    see ensure_baseline_saved() below — describe_config_for_humans calls
    it once it already knows configs_dir has real content (the config
    being described), and the config-picker 'v' keybinding calls it
    directly before pushing ConfigDiffScreen."""
    return compute_config_hash(baseline_config())


def ensure_baseline_saved(*, configs_dir: Path = DEFAULT_CONFIGS_DIR) -> str:
    """Persists the baseline config if it isn't already there (idempotent,
    like any save_config call — see target_system/config.py) and returns
    its hash. Use this, not default_baseline_hash(), right before loading
    the baseline by hash — e.g. before pushing ConfigDiffScreen."""
    return save_config(baseline_config(), configs_dir=configs_dir)


def describe_config_for_humans(
    config_hash: str,
    *,
    configs_dir: Path = DEFAULT_CONFIGS_DIR,
    baseline_hash: str | None = None,
    max_inline_diffs: int = 2,
) -> str:
    """One-line, human-readable description of a saved config, generated by
    diffing it against the baseline config using the exact same diff walk
    Manage Configs' diff screen uses (diff_configs, below) — never
    hand-authored per config. The raw config_hash never appears in the
    returned string; callers show it separately, demoted.

    A reconstructed config (provenance is not None) short-circuits this
    entirely: diffing a real reconstructed environment against the toy
    baseline produces a wall of unrelated field changes (different agent
    structure, different tools, a giant provenance blob — see
    tui.formatting's provenance diff entry) that says nothing useful about
    what the config actually is. "reconstructed: <source_agent_name> (<n>
    traces)" is what's actually informative here, everywhere this
    function's result is already shown (config picker, diff headers,
    comparison names — Part 6's labeling pass)."""
    baseline_hash = baseline_hash or default_baseline_hash(configs_dir=configs_dir)
    if config_hash == baseline_hash:
        return "baseline (defaults)"
    try:
        config = load_config(config_hash, configs_dir=configs_dir)
    except FileNotFoundError:
        return "(config details unavailable)"
    if config.provenance is not None:
        source = config.provenance.source_agent_name or "(no agent_name tag)"
        return f"reconstructed: {source} ({config.provenance.trace_count} traces)"
    # config_hash is already known to be a real, saved config at this point
    # (load_config above succeeded), so configs_dir is never "empty" here —
    # persisting baseline alongside it to make the diff possible has no
    # bearing on any empty-store check.
    ensure_baseline_saved(configs_dir=configs_dir)
    entries = diff_configs(baseline_hash, config_hash, configs_dir=configs_dir)
    return describe_config_diff(entries, max_inline_diffs=max_inline_diffs, target_agent_count=len(config.agents))


@dataclass(frozen=True)
class ConfigDiffEntry:
    path: str
    value_a: Any
    value_b: Any


_MISSING = object()


def _diff_value(path: str, a: Any, b: Any, out: list[ConfigDiffEntry]) -> None:
    if path == "agents" and isinstance(a, list) and isinstance(b, list):
        _diff_agent_list(path, a, b, out)
        return
    if isinstance(a, dict) and isinstance(b, dict):
        for key in sorted(set(a) | set(b)):
            sub_path = f"{path}.{key}" if path else key
            _diff_value(sub_path, a.get(key, _MISSING), b.get(key, _MISSING), out)
        return
    resolved_a = None if a is _MISSING else a
    resolved_b = None if b is _MISSING else b
    if resolved_a != resolved_b:
        out.append(ConfigDiffEntry(path, resolved_a, resolved_b))


def _diff_agent_list(path: str, a: list[dict], b: list[dict], out: list[ConfigDiffEntry]) -> None:
    """Diffed by role rather than list position, so "arm B adds a fourth
    agent" reads as one added-agent entry rather than a garbled
    positional mismatch across every agent after it."""
    by_role_a = {agent["role"]: agent for agent in a}
    by_role_b = {agent["role"]: agent for agent in b}
    for role in sorted(set(by_role_a) | set(by_role_b)):
        agent_a = by_role_a.get(role)
        agent_b = by_role_b.get(role)
        sub_path = f"{path}[role={role}]"
        if agent_a is None or agent_b is None:
            if agent_a != agent_b:
                out.append(ConfigDiffEntry(sub_path, agent_a, agent_b))
        else:
            _diff_value(sub_path, agent_a, agent_b, out)


def diff_configs(hash_a: str, hash_b: str, *, configs_dir: Path = DEFAULT_CONFIGS_DIR) -> list[ConfigDiffEntry]:
    """Every field where the two resolved configs differ, label excluded
    (label isn't part of the experimental condition — see
    target_system/config.py's compute_config_hash). Empty list means the
    two hashes really do resolve to identical content."""
    config_a = load_config(hash_a, configs_dir=configs_dir)
    config_b = load_config(hash_b, configs_dir=configs_dir)
    dump_a = config_a.model_dump(mode="json", exclude={"label"})
    dump_b = config_b.model_dump(mode="json", exclude={"label"})
    out: list[ConfigDiffEntry] = []
    _diff_value("", dump_a, dump_b, out)
    return out


def describe_comparison_for_humans(
    report: dict[str, Any], experiment_name: str, *, configs_dir: Path = DEFAULT_CONFIGS_DIR
) -> str:
    """The human-facing name for a comparison run. Ad hoc (wizard-driven)
    comparisons get a generated "X vs. Y" from each arm's config
    description — their auto-generated adhoc_<hash>_<hash> name (see
    tui.execution.comparison_experiment_name) is only a cache key and means
    nothing to a reader; the underlying filename is untouched, this only
    changes what's displayed. Presets keep their own curated
    experiment_name (e.g. "known_regression"), display-mapped through
    formatting.preset_display_name for the couple that need it."""
    if not experiment_name.startswith("adhoc_"):
        return preset_display_name(experiment_name)
    desc_a = describe_config_for_humans(report["arm_a_hash"], configs_dir=configs_dir)
    desc_b = describe_config_for_humans(report["arm_b_hash"], configs_dir=configs_dir)
    return f"{desc_a} vs. {desc_b}"


# --- unified past-runs listing ------------------------------------------------


@dataclass(frozen=True)
class RunListing:
    kind: Literal["comparison", "single_config"]
    name: str  # experiment name for comparison runs, config_hash for single-config runs
    created_at: float  # file mtime, for sorting/display — same convention as list_config_hashes
    comparison_report: dict[str, Any] | None = None
    comparison_verdict: ComparisonVerdict | None = None
    single_summary: SingleConfigSummary | None = None


def _list_comparison_runs(runs_dir: Path) -> list[RunListing]:
    listings = []
    for path in runs_dir.glob("*_report.json"):
        name = path.stem[: -len("_report")]
        report = load_experiment_report(name, runs_dir=runs_dir)
        if report is None:
            continue
        listings.append(
            RunListing(
                kind="comparison",
                name=name,
                created_at=path.stat().st_mtime,
                comparison_report=report,
                comparison_verdict=compute_comparison_verdict(report),
            )
        )
    return listings


def _list_single_config_runs(runs_dir: Path, configs_dir: Path) -> list[RunListing]:
    listings = []
    baseline_hash = default_baseline_hash(configs_dir=configs_dir)
    for path in runs_dir.glob(f"{SINGLE_CONFIG_RUN_PREFIX}*.jsonl"):
        config_hash = path.stem[len(SINGLE_CONFIG_RUN_PREFIX) :]
        records = list(read_run_records(path))
        if not records:
            continue
        description = describe_config_for_humans(config_hash, configs_dir=configs_dir, baseline_hash=baseline_hash)
        summary = compute_single_config_summary(
            [r.model_dump(mode="json") for r in records], config_label=description, config_hash=config_hash
        )
        listings.append(
            RunListing(
                kind="single_config",
                name=config_hash,
                created_at=path.stat().st_mtime,
                single_summary=summary,
            )
        )
    return listings


def list_all_runs(*, runs_dir: Path = DEFAULT_RUNS_DIR, configs_dir: Path = DEFAULT_CONFIGS_DIR) -> list[RunListing]:
    """One entry per run on disk — comparison experiments (anything with a
    _report.json) and single-config checks (single_<hash>.jsonl) merged
    into one newest-first list, each carrying its already-computed
    verdict so "View past runs" can render the tier straight from this
    without a screen recomputing anything itself."""
    if not runs_dir.exists():
        return []
    listings = _list_comparison_runs(runs_dir) + _list_single_config_runs(runs_dir, configs_dir)
    return sorted(listings, key=lambda listing: listing.created_at, reverse=True)
